### PR TITLE
Solves #65 HubSpot API-key sunset

### PR DESCRIPTION
**Pull request by lars-erik**
See #65

### CODE REVIEW

**Comment by acoumb** [comment]
Hi @lars-erik 
If my understanding is correct, with this PR, you enable users to use the access token of their private apps instead of the API key?

If so, wouldn't be best to use the access token of a private app as the third authentication method, maybe introduce a new setting in the site's configuration, and leave the API key as well? Although HubSpot specifies that using the API keys are a security risk, but I am thinking that maybe users who use it already might accept the risk and keep the configuration as it is.

Thank you

**Comment by lars-erik** [comment]
Hey @acoumb,  
HubSpot has _discontinued_ support for a single API-key, I don't see the reason to leave the option in. :P  
https://developers.hubspot.com/changelog/upcoming-api-key-sunset

**Comment by lars-erik** [comment]
Well, it's just a matter of time before it's completely turned off, and "fixing" requires like 5 clicks in your HubSpot portal after which you have a new key to copy into your configuration.  

The people who insist could just postpone upgrading this package as well?

**Comment by acoumb** [comment]
Sounds good, merging it.

**Comment by lars-erik** [comment]
Awesome, thanks! :)

**Pull request merged**
