### PR TITLE
Updated convertes, index value retrieval and UI fix.

### PR DESCRIPTION
**Pull request by acoumb**
Current PR addresses some of the issues raised [here](https://github.com/umbraco/Umbraco.Cms.Integrations/issues/191), which impacted the dashboard UI and data indexing.

Two changes are included with this minor release, one to the UI fixing the card deselected event, and the main one to the way converters behave.

I have removed the `indexValues` parameter of `IAlgoliaIndexValueConverter.ParseIndexValues` and work directly with the property. The `IProperty` parameter was included with the previous update of Algolia, and it would make sense to use it directly and not the index values returned by the CMS index value factory. 

To that extend, I moved the converters to run first, then to move to the editor's index value factory from CMS.

### CODE REVIEW

**Comment by Brandon-Hale** [comment]
Hey Guys, we have run into an issue with the RTE text not being picked up in the algolia data but just an empty string. I believe on Umbraco 13 and version 2.1.5 on the search algolia which in this I can see is moved to 2.2.0 but hasn't been merged as of yet. Trying to find a work around currently but this seems like it would fix issues we have, also cant upgrade to version 3.0.0 as it requires Umbraco 14. Hopefully this can get merged soon :)

**Comment by acoumb** [comment]
Hi @Brandon-Hale ,
Version 2.2.0 of Algolia is still a work in progress, I will revisit it in the following days. In the meantime, maybe it will help with your use case to create a custom converter for the RTE as detailed [here](https://docs.umbraco.com/umbraco-dxp/integrations/algolia#version-2.1.5-and-up).
Thank you,
Adrian

**Comment by Brandon-Hale** [comment]
Thankyou for this, didnt see this before and sure it will be very helpful. Will keep an eye out thanks again

**Comment by Brandon-Hale** [comment]
> Thankyou for this, didnt see this before and sure it will be very helpful. Will keep an eye out thanks again

Just on this the Core Variable in: public string Name => Core.Constants.PropertyEditors.Aliases.Tags;

isnt being recognised any ideas?

**Comment by acoumb** [comment]
You cannot find it in `Umbraco.Cms.Core.Constants.PropertyEditors.Aliases`? You just need the name of the property editor - `Umbraco.Tags`

**Comment by Brandon-Hale** [comment]
Just needed Constants.x.x.xxx think becuase our namespace is Company.Umbraco.xx so it was just messing with the namespace

**Comment by Brandon-Hale** [comment]
`public class AngoliaIntegrationConverter : IAlgoliaIndexValueConverter
{
	public string Name => Constants.PropertyEditors.Aliases.TinyMce;

	public object ParseIndexValues(IProperty property, IEnumerable<object> indexValues)
	{
		return new[] { "Umbraco", "is", "awesome" };
		//return new KeyValuePair<string, object>(property.Alias, indexValues);
	}
}`

Is this all thats needed to supposed to show up in Algolia for an RTE (still getting "")? On version 2.1.5 (https://docs.umbraco.com/umbraco-dxp/integrations/algolia#version-2.1.5-and-up) the issue is mentioned on it but doesnt seem to solve it.

**Comment by acoumb** [comment]
You will need to add your new converter like this
image

**Review by AndyButland — APPROVED** [review]

**Pull request merged**
